### ISSUE TITLE
Remove bh.algorithm

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#197]
Since the functions are methods on the histogram, this module can be removed. It only needs to exist in the cpp module.

**Comment by HDembinski** [comment]
To clarify:
* remove `bh.algorithm`
* keep `bh.cpp.algorithm`

The `bh.cpp.histogram` should not have a `.reduce` or `.project` method

**Comment by henryiii** [comment]
We can and should remove the free functions from the direct library. The CPP version already does not have some of the functions. The slice parts are needed, however, to construct slices based on axis instead of using UHI to pass into reduce, so a part of the module would still be there. 

PS: I spoke to someone at CHEP who specifically needs these since sometimes you know what axis you need to operate one in a large (5+) set and UHI is not useful in his case.

**Comment by HDembinski** [comment]
With "slice parts" you mean `.reduce`?

**Comment by HDembinski** [comment]
I would be in favor of not having `.reduce` and `.project` in the Pythonic module at all if the functionality can be completely provided by the UHI interface, but if one of those two methods has to stay, probably both should stay.

**Comment by henryiii** [comment]
It's quite hard to perform operations like "Please slice dimension 8" of an ND histogram or "please project to Axis 5" of an ND histogram.

Also, you can't change the order of the result with UHI, but I think you can with `.project`.

UHI is for when you know what you want to do axis by axis. `.project` and `.reduce` are for when you know what to do on a set of 1 or more axis. I think they are not fully orthogonal in use, but have orthogonal components, especially for large numbers of dimensions.

**Comment by HDembinski** [comment]
Ok.
