### ISSUE TITLE
Change C++ style

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#199]
I don't care much about the white-space in boost-histogram being different from Boost.Histogram, but there is one thing that is very irritating with the current style. The `&` and `*` are part of the type and should be adjacent to the type.
`const T& foo(const char* string)` or `T const& foo(char const* string)` if you want to be uber correct, but not `const T &foo(const char *string)` or `T const &foo(char const *string)`. When development has settled down a bit, I will make a PR to change this.

**Comment by HDembinski** [comment]
Boost.Histogram uses `const T& foo(const char* string)`, as do large parts of Boost.Core. The other style found in Boost.Core is `const T & foo(const char * string)`.

**Comment by henryiii** [comment]
This is fine with me. I've never fine-tuned the style; I picked one I had used somewhere else in a PyBind11 project, and I think was based on LLVM. I prefer `const T& foo` over `const T & foo`, and both over with `const T &foo`, with the understanding that one never defines multiple items on the same line (since the C++ (from C) language attaches the modifier to the object instead of the type - the choice would not be ambiguous if it didn't).

If you see other modifications that help readability, go ahead and propose them as well.

**Comment by HDembinski** [comment]
Good summary of the issue. I don't know why LLVM chose the C-ish style.

**Comment by henryiii** [comment]
Look at the main sample on [clang-format's page](https://clang.llvm.org/docs/ClangFormatStyleOptions.html). It's LLVM style, but with the pointer alignment changed. :)

Otherwise, LLVM's style suggestions tend to be quite good. https://llvm.org/docs/CodingStandards.html

**Comment by henryiii** [comment]
I can't now unsee it:

```c++
const RealType &count() const noexcept { return sum_; }
```

**Comment by HDembinski** [comment]
Welcome to the club ;)

**Comment by HDembinski** [comment]
Yes, that's interesting, that even on the clang-format page they change the alignment.
