### ISSUE TITLE
cmake should default to debug build

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#225]
cmake defaults to release, but cmake builds are only done by developers. doing a debug build by default seems more natural.

**Comment by henryiii** [comment]
This just seems really odd, but I see why it would make sense. Should it be `RelWithDebInfo` or `Debug`? I often develop in Release, since I like the tests running faster (but, okay, a couple of seconds versus under a second is not that big of a deal), but the linking step takes much longer in Release mode, so I've started building in Debug more often.

**Comment by HDembinski** [comment]
The linking in release mode probably takes longer because of the LTO step. That would be one more reason to default to Debug mode. I need debug mode when I debug the C++ code. RelWithDebInfo is not helpful, because functions get inlined and then I cannot set breakpoints there (and the control flow is confusing).
