### ISSUE TITLE
cmake does not update python files

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#240]
The cmake build makes a copy of the Python files in the build folder, but never updates this copy on `make` even if the sources change.

**Comment by henryiii** [comment]
As long as you use CMake 3.14+, the files are symlinked in and don't need updates. It doesn't pick up added/removed files, though, unless the configure step is rerun (when it also should update the files for older CMakes, I think).

**Comment by henryiii** [comment]
This should be looked into, but it's really not going to be usable on CMake 3.10-3.13 for proper Python development, since running a command every time you change a Python file is irritating; and really, the name of the command is all that would change; currently, you have to run cmake to update the Python files instead of make.

Also, another gotcha is that it can't delete Python files that have been deleted in the source.

**Comment by HDembinski** [comment]
If the issue is solved in newer versions of cmake then that's fine. I can just update cmake.
