### ISSUE TITLE
remove `storage::int_`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#241]
Our compile times are very large and removing this storage will help. The speed is the same as `storage::double_` and until the mantissa is full (which has some 40+ bits), double is an exact representation of an integer.

**Comment by henryiii** [comment]
Numpy goes through quite a bit of work to use ints internally, then convert to doubles at the end, specifically so that the histogram is not limited to the double mantissa. We probably should look up the original issue where that was requested to see why it was important.

**Comment by henryiii** [comment]
Also, when someone actually wants a count, ints are much more natural. Exact comparison with a double is generally frowned upon, for example. Ints also use ALUs instead of FPUs, so they have a different impact on hyperthreading. Also, it's won't drop our compilation time by more than 1/7th. It might be better to look into other ways of improving our compile time. We probably will need to carefully consider atomics; we might want (only?) atomic double.

**Comment by HDembinski** [comment]
There is no atomic double, I think.

I still think we should drop storage::int_. We checked in the benchmarks that double storage is as fast as storage int, so I don't see the case regarding hyperthreading. Considering that my computer is almost running out of memory and takes forever to compile register_histogram.cpp, I am very much interested in gaining a 1/7 th, especially since there is no clear use case for `storage::int_`. I am not saying you should remove `storage::atomic_int`.

Also, once I am done filling my histogram I almost immediately want to do some calculations with it, and then the counts are almost always converted to double anyway.

**Comment by HDembinski** [comment]
A while ago I even checked how large the number is that the mantissa can hold and it is very large. It was larger than any count I would expect to get at the LHC. I don't want to repeat the calculation here.

**Comment by HDembinski** [comment]
> Also, when someone actually wants a count

No one cares about the dtype if it does the job and is fast.

**Comment by henryiii** [comment]
> There is no atomic double, I think.

You can make one, but before C++20, it isn't required to have add, which is kind of a problem.

Do we really need unlimited? It is not nearly as useful as the C++ version, since it internally converts to double as soon as you try to access it, and adds complexity to the bindings (and probably more compile-time reduction than int). It seems like int might be more useful (giving actual int arrays from view) than unlimited. Certainly, if one should go, I think it should be unlimited (and if two go, then both unlimited and int).

We will lose full correspondence with ROOT histograms if we drop int storage (As ROOT has TH1D and TH1I). Also, 1D numpy histograms are ints (2+ internally are ints, but convert to double sadly - this is a bug people complain about because they expect counts to be ints but it hasn't changed yet).

It takes 150 years for a 4Ghz processor to overflow a 64 bit integer, assuming +1 operations only. It takes 26 days to overflow a double. If you have a hot pixel, you can end up with quite a heavy count in one bin...

> No one cares about the dtype if it does the job and is fast.

Double is the wrong datatype if you are counting something. `for(double i=0; i<10; i++)` is valid but not ideal, since `i` is a count and the datatype reflects this.

**Comment by henryiii** [comment]
How about we rename Int to Int64, then eventually add Int32 and Int16? Those would be faster and smaller, and would have at least some use cases (I have 100s of GB of 16-bit integer 4D 18M bin histograms for my thesis work at UT).

**Comment by HDembinski** [comment]
> You can make one, but before C++20, it isn't required to have add, which is kind of a problem. So yes, this is the only one.

You can make one, but you cannot increment or add. So essentially, it is unusable, which is what I remember from looking into this.
https://godbolt.org/z/b-XY6V

**Comment by HDembinski** [comment]
Once we solved the issue of compilation times, we can add more int storages. For now, if you want to safe memory, use the unlimited storage.

**Comment by HDembinski** [comment]
> Do we really need unlimited? It is not nearly as useful as the C++ version, since it internally converts to double as soon as you try to access it, and adds complexity to the bindings (and probably more compile-time reduction than int). It seems like int might be more useful (giving actual int arrays from view) than unlimited. Certainly, if one should go, I think it should be unlimited (and if two go, then both unlimited and int).

One of the goals of boost::histogram was to allow people to not worry about the counters. Unlimited gives you safe counting, so you don't have to care. That it converts to double is not an issue. Converting to double is an advantage, as I have told you. When you compute anything with a histogram, you convert to double anyway. Tell me please what the problem is with having double counters, because I have not heard an argument that makes any sense so far.

**Comment by HDembinski** [comment]
We also need unlimited for advertising. It is one feature that is unique to us, that other libraries do not have. You should point this out when you give talks about boost-histogram.

**Comment by HDembinski** [comment]
With you idea of adding lots of int storages you are undoing some of the goals of boost::histogram, namely that people should not have to care about the counters. We do not need parity with ROOT histograms, because ROOT histograms are not well designed. I don't want to overwhelm users with lots of choices. I think for histograms (not profiles), we need double storage, weight storage, and unlimited. These cover all the use cases. double is a good default, weight storage you need for weighted simulations, and unlimited covers the case when you want to converse memory.

**Comment by HDembinski** [comment]
> It takes 150 years for a 4Ghz processor to overflow a 64 bit integer, assuming +1 operations only. It takes 26 days to overflow a double. If you have a hot pixel, you can end up with quite a heavy count in one bin...

Exactly, overflowing a double never happens in real life.

**Comment by HDembinski** [comment]
Also, regarding the conversion of unlimited to double, I thought this was something that we agreed upon as the simplest and safest solution. Now it sounds like you don't like it this compromise. My original python bindings only converted the view for unlimited to double when it was in the unlimited state, because that one could not be represented. All integers were faithfully returned as integers, though. We can also go back to that solution if you prefer.

**Comment by HDembinski** [comment]
Do you have any ideas on #247 ? I think this would be nice to have for 1.0.

**Comment by henryiii** [comment]
It seems like you are arguing you can't overflow double (26 days), and that we have to have a way to cover overflowing int (150 years)? I'm not fond of features that are just for bragging rights and are not useful. It is no longer faster, which was the original point, and it can't be used to conserve memory, because even *just looking at it* turns it into 64 bits.

Users who select storages probably *want* to have control; otherwise they would use the default.  I am not against having an "Unlimited" as automatic method, but I'm just suggesting that if you are worried about compile times, that is a prime candidate to go first. It also increases the memory usage due to the workarounds we have put in place for it, while the int storage should not increase the total memory noticeably (they should get compiled mostly separately, you could break them in to individual files if needed).

> Now it sounds like you don't like it this compromise.

I only don't like it if int goes away, and there is not a way to access ints at all. It was a reasonable compromise to get this in.

> We do not need parity with ROOT histograms

If you remove ints, then downstream libraries (Hist, Physt, Coffea, etc) will not be able to offer Int histograms. Libraries like Aghast will not be able to do a round trip (ROOT -> boost-histogram -> ROOT) because ints get converted to doubles, then that becomes a TH1D.

Also, I'm using int storage for 1D `bh.numpy.histogram` method, since it needs to produce ints to match numpy. It will be slower if I have to copy the doubles into ints.

**Comment by henryiii** [comment]
Most users will be getting a 2MB wheel of a boost-histogram, and will be happy. Developers always have to deal with a bit of compile time; I'd love to improve that, but 3.2 minutes single threaded is not awful and is less than numpy or other major projects. It's much faster multithreaded and in debug mode.

I think there's enough of a reason to leave in int storage (maybe as Int64 to be clearer and forward thinking).

**Comment by henryiii** [comment]
We should decide on this before 0.6.0 as well.

**Comment by HDembinski** [comment]
> It seems like you are arguing you can't overflow double (26 days), and that we have to have a way to cover overflowing int (150 years)? I'm not fond of features that are just for bragging rights and are not useful. It is no longer faster, which was the original point, and it can't be used to conserve memory, because even just looking at it turns it into 64 bits.

The point is that double offers enough capacity, we don't need int64. double is a very good integer. unlimited is not useless, because you do not view the histogram while you are filling it. Also, we can avoid the conversion to double with a more clever view. I am also happy to go back to the original solution which I had implemented, where the view does not trigger a transform of the storage.

You criticised the old view and pushed for conversion to double and now you use this as an argument to get rid of unlimted, wtf?

**Comment by HDembinski** [comment]
unlimited is great, because when you fill a histogram for the first time, you don't know a priori how large the counts per bin are going to be. unlimited allows you to not worry about this. It's main point was not to be fast, but to offer this worry-free guarantee, which it still has. Of course it has to be fast as well.

**Comment by HDembinski** [comment]
> I only don't like it if int goes away, and there is not a way to access ints at all. It was a reasonable compromise to get this in.

Then let's improve the view so you can get ints.

> Also, I'm using int storage for 1D bh.numpy.histogram method, since it needs to produce ints to match numpy. It will be slower if I have to copy the doubles into ints.

Also solved by unlimited with a proper view.

> If you remove ints, then downstream libraries (Hist, Physt, Coffea, etc) will not be able to offer Int histograms. Libraries like Aghast will not be able to do a round trip (ROOT -> boost-histogram -> ROOT) because ints get converted to doubles, then that becomes a TH1D.

That would be a feature and not a bug. doubles have enough bits in the mantissa for all purposes and once you are done filling the histogram, you often want to scale it or normalize it or compute some density, all these operations convert to double.

The main problem here is that people do not understand how doubles work and think that doubles are not precise. Instead of supporting this superstition, you should help me fight it.

**Comment by HDembinski** [comment]
> if you are worried about compile times, that is a prime candidate to go first. It also increases the memory usage due to the workarounds we have put in place for it, while the int storage should not increase the total memory noticeably (they should get compiled mostly separately, you could break them in to individual files if needed).

Do you have any proof for this? We have to generate a full histogram and a full histogram wrapper in Python for each storage. The int storage itself is comparably compact, since it is essentially a vector, but all that other stuff attached to it drive the memory and computation cost, I would think.

**Comment by HDembinski** [comment]
At least I know now what your real reasons are for being against removing int.

> If you remove ints, then downstream libraries (Hist, Physt, Coffea, etc) will not be able to offer Int histograms. Libraries like Aghast will not be able to do a round trip (ROOT -> boost-histogram -> ROOT) because ints get converted to doubles, then that becomes a TH1D.

> Also, I'm using int storage for 1D bh.numpy.histogram method, since it needs to produce ints to match numpy. It will be slower if I have to copy the doubles into ints.

These are the real arguments, everything else are straw men.

**Comment by HDembinski** [comment]
If you fill from an array of reasonable size e.g. [10000], the computation time is dominated by the filling and the conversion is negligible. I tested this the other day myself.

**Comment by HDembinski** [comment]
> I'm not fond of features that are just for bragging rights and are not useful. It is no longer faster, which was the original point

That comment I find extremely rude and very upsetting. I never do anything just to brag about it. 

1) This is about having a unique feature that we can advertise, not bragging. That's how advertisement works. You can't tell people that your library is the best designed, because people don't understand that. But they understand that you have unique features and they understand that your library is fast. We want to stand out and these things can be easily demonstrated. You cannot easily demonstrate good design, because most people are not able to recognize good design at a glance. Once they start to use the library, they will feel the comfort of good design, however, but they won't be able to pinpoint why the library is so comfortable to use.

2) The unlimited storage is still useful even if it is not the fastest around, because it solves the original problem of not having to worry about which integer to use for my histogram. unlimited still offers great memory savings for high-dimensional histograms, up to a factor of 8. How fast it is actually depends on the compiler and the processor architecture. I get rather different performance on my laptop and home and my work laptop.

I will tune out of this discussion for now and come back later. Please do not write anything rash again like "you are adding features to brag about". I'll have you know that developing unlimited cost me a ridiculous amount of time, and even so I am willing to drop it as the default for a simple double storage, because doubles are nicer than I initially realized. I am modest enough to change my mind when presented with hard evidence, are you?

**Comment by HDembinski** [comment]
I am closing this. Eventually we will have all kinds of intX storages, because people will ask for this. I mainly brought this up as a temporary fix for the compilation issue. I don't want to hear again about removing unlimited. You should really advertise this storage more.

**Comment by henryiii** [comment]
Please don't take this the wrong way, I don't dislike unlimited or think it should be removed. I was just saying that it sounded like you were arguing "doubles are good enough for everything" and "we need unlimited because 64-bit ints are not good enough". Until we provide some way for users to get a numpy array of ints from unlimited, we can't advertise them as storage efficient; simply looking at the contents will cause them to pop up to 64 bits doubles and lose any benefits over double. And this caveat is not part of the C++ version, where they can be very useful and unique. And there probably is a way to make this work better in Python, we should not give up there quite yet.
