### ISSUE TITLE
restructure header files

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#242]
The header structure is non-standard. Standard header structure looks like this:
```
#include <boost/something/external_header.hpp>
#include "internal_header.hpp"
```
- internal headers should use quotes
- the `boost/histogram/python` prefix is superfluous and should be removed

**Comment by HDembinski** [comment]
See #243, which is pending on #239

**Comment by henryiii** [comment]
The current structure was inspired by the original bindings. Simpler, more standard structure sounds good.

**Comment by henryiii** [comment]
> internal headers should use quotes

On most compilers, this means relative includes are searched first; that's so common, in fact, that my IDE (XCode) no longer suggests completions for the files in the src directory because it's only suggesting things in the same directory. What about adding a simple folder, like "/include/bh_python", and then using `<bh_python/...>`?

This is also a bit safer; if we added a subfolder in a subfolder with the same name, `<>` is completely unambiguous but `""` is not if it is not used relatively. I've run into this problem in the wild; ROOT can be in a roto folder and has a ROOT subfolder (in recent versions), and on a case-insensitive filesystem (Windows and macOS), the include can change meanings.

**Comment by HDembinski** [comment]
Sure, I am ok with this. How about calling it just `bh` to keep it short? Or `bh`? Or `local`?

**Comment by HDembinski** [comment]
I am also ok with a longer name in principle. My main issue with the previous folders what that there are three levels of depth.

**Comment by henryiii** [comment]
Agreed, that was quite overkill. Given that we call this `bh` most of the time in Python, I like `bh` best, though `bhp` is not bad either. A general name like `local` does not convey that this is boost-histogram. This will actually make the IDE view much nicer than either it was before or now.
