### ISSUE TITLE
Consistency in flow

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#25]
Currently, many methods support flow=bool, but the default might not be consistent. Here are the options:

1. Make flow=True the default everywhere. Then a user can use `regular_noflow` if they really want to avoid the under/overflow bins, or use `flow=False` manually everywhere.
    * Possible followup: rename `regular_noflow` to `regular`, and `regular` to `regular_flow` or similar.
2. Make `flow=False` the default everywhere. This makes the overflow basically a detail that doesn't bother users unless they ask for it, but doesn't force them to turn it off completely.
3. Be inconsistent about usage and confuse everyone.

I think we are choosing option 2. This includes changing np.asarray to ignore flow bins.

**Comment by HDembinski** [comment]
Jim pushed me to make both underflow and overflow bins individually optional, which is what we have now. So a boolean for `flow` does not reflect the flexibility that Boost::Histogram provides.

I think `regular` in boost-histogram should be function instead of a class, which returns the right kind of static regular type.

```python
def regular(bins, start, stop, underflow=True, overflow=True):
    if underflow and overflow:
        return regular_uoflow(bins, start, stop)
    if underflow:
       return regular_uflow(bins, start, stop)
    if overflow:
       return regular_oflow(bins, start, stop)
    return regular_noflow(bins, start, stop)
```

**Comment by henryiii** [comment]
The problem is that this adds a lot of different possibilities - each combination needs a binding and an entry in the any variant. It also tricks users into thinking they can mix flow and no flow (or underflow/overflow) and this causes a huge hit on performance by dropping back to the any variant.

**Comment by HDembinski** [comment]
> Using regular(flow=True) tricks users into thinking they can mix flow and no flow

They should be able to. I see no problem falling back to slower the variant version. It is not that much slower, just a factor of two.

**Comment by HDembinski** [comment]
> Also, I'm not fond of functions masquerading as classes. While it's not Pythonic, someone might do something like isinstance(ax, regular) and that won't work at all. (Note: I could be convinced otherwise, it's not a huge issue.)

Agreed, it is not ideal. The alternative is to have a regular class which is just a shell that forwards the calls to the internal implementation, which is then an instance of the specialized classes.

```py
class regular:
   def __init__(self, args, foo=True):
       if foo:
            self.impl = regular_foo(args)
       else:
            self.impl = regular_nofoo(args)
```

**Comment by henryiii** [comment]
What about all the function versions of regular (log, sqrt, power)? Should integer and variable also have noflow, uflow, oflow, and uoflow versions? Circular could have one too. What is the reason to drop the overflow bins other than for performance (often smaller than factor 2), expecially if you can easily ignore them?

**Comment by HDembinski** [comment]
The option to turn off the *flow bins is mostly provided for optimization freaks and pedantic people. A pedantic person would say that a regular axis which bins radii should not have an underflow bin, because a radius is always a non-negative number.

The default should always be with *flow bins, they do not practically harm you in most cases. Anyway, I think the "slow" versions based on variant could support all these combinations.
