### ISSUE TITLE
Index Error

### ISSUE THREAD

**Issue by LovelyBuggies** [scikit-hep/boost-histogram#319]
Get item index error: https://github.com/henryiii/mini_hist/issues/2#issue-572520900

**Comment by henryiii** [comment]
The problem is that slices are (currently) required in the `{}` syntax; it is broken if there is a non-slice (a mistake, but historically it was not possible to mix, so I understand why the bug happened when mixed slices and indexes became allowed). There is a second bug where all indexes is also not allowed, which was an oversight because that's rather odd usage.
