### ISSUE TITLE
CMake build fails

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#330]
I made some changes to reduce.hpp in Boost.Histogram and I wanted to see whether this affects boost-histogram and potentially fix it. However, I cannot build with cmake.

```
-- The CXX compiler identification is Clang 9.0.1
-- Check for working CXX compiler: /usr/local/Caskroom/miniconda/base/bin/x86_64-apple-darwin13.4.0-clang++
-- Check for working CXX compiler: /usr/local/Caskroom/miniconda/base/bin/x86_64-apple-darwin13.4.0-clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Debug' as none was specified.
-- CMake 3.16.2
-- Found PythonInterp: /usr/local/Caskroom/miniconda/base/bin/python3.7 (found version "3.7.6")
-- Found PythonLibs: /usr/local/Caskroom/miniconda/base/lib/libpython3.7m.dylib
-- pybind11 v2.4.3
-- Python 3.7
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
CMake Error at CMakeLists.txt:180 (message):
  Dependencies missing, try installing:

    /usr/local/Caskroom/miniconda/base/bin/python3.7 -m pip install setuptools_scm

Call Stack (most recent call first):
  CMakeLists.txt:194 (python_import)


-- Configuring incomplete, errors occurred!
```
I installed setuptools_scm and I can import it, but the error remains. Not sure what is going on.

**Comment by HDembinski** [comment]
`pip install -e .` seems to work, but I get compilation errors due to my changes, as expected, since boost-histogram is using the details of reduce. I am happy to work on the patch, but I need the cmake build to work for that.

**Comment by henryiii** [comment]
That's odd, it should just be trying to import setuptools_scm. If you want to work around it, all you have to do is add a version.py file to `src/boost_histogram` with `version=<something>`, and it will start working again - but I'd rather fix the bug.

**Comment by henryiii** [comment]
If you run `/usr/local/Caskroom/miniconda/base/bin/python3.7 -c "import setuptools_scm` (full path), does that succeed or fail?

**Comment by henryiii** [comment]
If you are in an environment, you need to tell CMake about the environment with `-DPYTHON_EXECUTABLE="$(which python)"` - this could have been fixed if we used the new FindPython in CMake (which recently even started supporting conda environments), but PyBind11 doesn't use them so we don't.

**Comment by HDembinski** [comment]
Maybe that's the reason yes, I am in a venv environment inside a conda environment

**Comment by henryiii** [comment]
Try reconfiguring with the correct Python base interpreter (it should be the one from the venv) and see if that fixes it.

**Comment by HDembinski** [comment]
```
/usr/local/Caskroom/miniconda/base/bin/python3.7 -c "import setuptools_scm"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'setuptools_scm'
```

**Comment by HDembinski** [comment]
Ok, will do

**Comment by henryiii** [comment]
Yes, I'm guessing setuptools_scm is not installed in your base env (it is generally recommended not to install anything in your base env).

**Comment by HDembinski** [comment]
Yes, works like a charm now. I remember how broken FindPython is, glad to hear that the cmake guys improved it. Can we please add a section to docs on how to compile from source with this workaround?

**Comment by henryiii** [comment]
https://github.com/scikit-hep/boost-histogram/blob/develop/CONTRIBUTING.md#cmake ?

**Comment by henryiii** [comment]
> I remember how broken FindPython is, glad to hear that the cmake guys improved it. 

Technically FindPythonInterpreter and FindPythonLibs, and yes, they were very broken and the new FindPython is much better. Though now they will not fix bugs in those two find modules because the replacement exists.

**Comment by henryiii** [comment]
If we moved to FindPython, we could (I believe) drop the `PYTHON_EXECUTABLE` setting *and* the `DCMAKE_INSTALL_PREFIX` workaround (to allow installing into site-packages), since FindPython respects the current python and provides the site packages directory. But we would be limited to a *very* new CMake version, and we'd have to reimplement any special settings added by PyBind11, such as the visibility setting. Something to think about in the distant future (maybe around when CMake 3.18 or so comes out, so we can support the last 3 CMake versions or something like that).

**Comment by HDembinski** [comment]
I think the work around is ok for now, but it should be documented.

**Comment by HDembinski** [comment]
I see now that they really changed it to `FindPython`, I thought you were abbreviating before. Very good, this split between FindPythonStuff was a big mistake.

**Comment by henryiii** [comment]
Yes, especially since a common bug was that `FindPythonInterpreter` and `FindPythonLibs` could find *different* versions of Python! Bugs like that have been fixed in PyBind11's modified copy of those libraries, but CMake properly rewriting them was better. Just a shame that people like using older versions of CMake.[^1]

> I think the workaround is ok for now, but it should be documented.

Should there be more than what is found in CONTRIBUTING.md? Should we put more links to CONTRIBUTING in somewhere or something else? Happy to fix, but I'm too familiar with it to know where people are looking for dev docs. GitHub recommends CONTRIBUTING.md when you try to contribute.

[^1]: I am aware of a bug in 3.16 with CUDA support that forces me to limit CMake to 3.15 for GooFit. But *most* of the time, they do a great job of being backwards compatible.
