### ISSUE TITLE
Smart slicing

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#35]
TODO: Add setting support

This will be closed when setting support is added, along with underflow/overflow.

The current version of this proposal lives here: <https://boost-histogram.readthedocs.io/en/latest/usage/indexing.html>.

**Comment by henryiii** [comment]
I'll be preparing a discussion for Aghast; I'll put it here for now while I work on it. The biggest issue I had in thinking about it was mixing "histogram" returns from "array" returns; I think if I restructure it to consider both as separate this will make more sense.

---

We've been discussing the smart binning (I'm interested in possibly even adding it to boost-histogram, of course it should be in hist but that could be through aghast). I had an idea about the under/overflow bins:

1D, no flow bins:

```python
h[:]
```

Underflow only:
```python
h[...:]
```


Both:
```python
h[...:...]
```

I just checked to see if this syntax was supported in Python itself, and it is (`...` is not allowed in many places, but slices are one of those places). This doesn't require `import numpy; np.inf` or `float('inf')`, and also follows the meaning fairly well. It also avoids supporting floats as indices but with special reservations - it's a singleton type. The downside is that visually it can be a little busy and unusual: `g[...:..., ...]` means under/overflow for the first axis, then all the rest of the axes without flow bins. A user could always spell out `Ellipsis` if they wanted to.


Another idea we played with was unique tokens for the special concepts; they are a little less surprising but are more verbose and hard to share across libraries:

```python
h[bh.flow:bh.flow]
h[::bh.rebin(2)] # Specify this will rebin rather than skip
h[:, bh.sum, ...] # Sum over an axis, instead of None
```

One problem I see with the current version and a new version is that `:` means without the flow bins (I think), so `h[:,None]` will remove the under/overflow bins.

**Comment by HDembinski** [comment]
When to make (design)decisions, I find it useful to explicitly spill out the criteria for making the decision.

To be unsurprising, NumPy fancy indexing on histograms should do the same as it does on NumPy arrays. The following should hold `array[fancy_indexing] == np.asarray(histogram[fancy_indexing])`

The problem is that the syntax `numpy_array[:, None, :]` and `numpy_array[::2]` are valid for numpy arrays, so giving this syntax a different meaning when its passed to a histogram is confusing. In Python, we like duck typing. This allows us to ignore the type in most cases (which is often not explicitly written either!), we don't have to mentally keep track whether my variable here is a histogram or a numpy array. I think this is a very important property.

We can avoid conflicts, if the new behavior is obtained with a new syntax which causes an error when used with normal NumPy arrays. That's why we suggest special tags like `bh.sum` or `bh.rebin(2)` to do projection and rebinning, respectively.

**Comment by henryiii** [comment]
### Histogram slicing

This can do histogram operations: projections, shrinking, and rebinning:

```python
h[...] # Copy of any dim histogram
h1d[0:len(h)] # Copy of 1D histogram; note that underflow/overflow always implicitly included
h1d[1:4] # New histogram with bins 1,2,3 and under/overflow now includes removed bins
h1d[::2] # Rebin; the "missing" or "skipped" bins get added to the appropriate neigbor bin, just like flow bins above
h[:, None, :] # This is the one ugly one, with the opposite meaning from numpy
```
Only slices are allowed (and the sum token, which is None in the above example but could be `bh.sum` or `bh.all` or similar, open for discussion). Histograms are not arrays, and are allowed to have slightly different syntax (as long as it is logically similar). Removing a bin in a histogram adds it somewhere else (in general), unlike numpy arrays.

No proposed syntax for doing this in data coords (at least, not yet).

---

### Array slicing

This would return arrays. This is the one where `array[fancy_indexing] == np.asarray(histogram[fancy_indexing])` is important. So for this one:

* Underflow/overflow is ignored unless included by a special syntax.

```python
h.iloc[...] # returns arrays with all flow bins removed
h1d.iloc[:] # No under/overflow
h1d.iloc[0:len(h)] # No under/overflow
h1d.iloc[...:....] # Include underflow/overflow
```

We could add special tokens here to allow rebinning and projections, but you can always combine:

```python
h[::2].iloc[:]
```

I don't think we need a shortcut for doing histogram operations and getting and array back in one. We just need a way to add under/overflow bins, which the above `...` in slices trick does.

Ideas for the token:

| Token | Pros | Cons |
|-------|------|------|
| `...`    | Simple, always available, is not unique to one library | Ugly (can use `Ellipsis` though), easy to mix with `,...` |
| `float('inf')` | Closest to the meaning of flow bins | Verbose, allowing only this floating point is odd, can come in +/- versions |
| `bh.flow` | Clear | Must be implemented for each library, hard to mix |

`.loc` could do this in data coords (and there inf is nicer).

**Comment by jpivarski** [comment]
I want to continue this on the Gitter as soon as I get on the train, but one thing we have to watch out for is that `...` has a definite meaning in Numpy (it was added to Python syntax for Numpy): a single `...` in a slicing tuple means as many empty slices as would fill up all dimensions of the array. In fact, I implemented it with that meaning in Aghast, but didn't include that in my talk. It's useful because `Collections` can include histograms with different numbers of dimensions, and `...` lets you access the last axes of all of them in a uniform way.

Switching over to Gitter now. (https://gitter.im/HSF/PyHEP-histogramming).

**Comment by henryiii** [comment]
@jpivarski, if you use Ellipsis like numpy, then it works like Numpy. The new thing here is using Ellipsis *in* a slicing expressions itself. This is not valid in Numpy, to the best of my knowledge: `arr[...:...]`, only this is: `arr[:, ...]`. The tuple can have slices in it, and up to one Ellipsis, but not elipsis in the slice. My first example creates a `slice(Ellipsis, Ellipsis, None)`.

**Comment by jpivarski** [comment]
Oh, that's right. It's weird, but you're right that it doesn't conflict with existing syntax. It might be too subtle of a distinction, though?

Let's collect ideas here: https://docs.google.com/document/d/1bJKA7Y0QXf46w53UFizJ4bnZlVIkb4aCqx6m2hoN0HM/edit?usp=sharing because we'll be able to edit down to a conclusion, rather than a stream of comments.

**Comment by HDembinski** [comment]
> This can do histogram operations: projections, shrinking, and rebinning:

> ### Histogram slicing
> 
> This can do histogram operations: projections, shrinking, and rebinning:
> 
> ```python
> h[...] # Copy of any dim histogram
> h1d[0:len(h)] # Copy of 1D histogram; note that underflow/overflow always implicitly included
> h1d[1:4] # New histogram with bins 1,2,3 and under/overflow now includes removed bins
> h1d[::2] # Rebin; the "missing" or "skipped" bins get added to the appropriate neigbor bin, just like flow bins above
> h[:, None, :] # This is the one ugly one, with the opposite meaning from numpy
> ```

I agree with the rest of Henry's post, but I disagree that it is ok to use NumPy slicing syntax differently for histogram. I already wrote down my argument above. Rebinning and projection should use a syntax that causes an error when applied to a normal NumPy array.

**Comment by HDembinski** [comment]
The Zen of Python says: "Explicit is better than implicit." and "Readability counts." and "Special cases aren't special enough to break the rules." and "There should be one-- and preferably only one --obvious way to do it."

**Comment by henryiii** [comment]
The first three lines are exactly the same as normal numpy syntax, just with under/overflow applied in the most logical way. The only line in question is the `[::2]`, where we've simply made the statement that "skipping" in a histogram makes no sense (Histgram return types must match, and they are continuous), so I think this is a reasonable enough adjustment on the normal syntax, and is no larger than some of the things Pandas does to slicing syntax (look at their time slices, for example).

Adding new terms imposes a larger learning requirement on the user, is not discoverable (unlike a method, where you can easily find it), and is unique to each library (bh::rebin is not the same as aghast.rebin or physt.rebin...).

Yes, I don't know what to do with the `None` and that's probably not going to stay. I just would like a non-specific solution - this may not be / probably is not possible. And `np.newaxis`  is simply `None`, so if we did use `None`, a user could write `np.newaxis` and have it remove an axis!

**Comment by HDembinski** [comment]
> Yes, I don't know what to do with the None and that's probably not going to stay. I just would like a non-specific solution - this may not be / probably is not possible. And np.newaxis is simply None, so if we did use None, a user could write np.newaxis and have it remove an axis!

Using `None` should raise an error for this reason. The syntax should be so that switching out a histogram with an array should either create an error or do the same on the array as on the histogram.

**Comment by jpivarski** [comment]
Keeping with Numpy usage (which Aghast 0.2.0 does not do), `None` would mean "create an axis with a single bin" (regular with no overflow/underflow, one bin from -infinity to infinity?). I can't think of any use for that, but it is the only way that an axis might be created, rather than projected away.

**Comment by henryiii** [comment]
> Using `None` should raise an error for this reason

Please see the description at the top for the current plan; the thread here is historic only. None is currently not allowed (will make that explicit) in the histogram syntax.
