### ISSUE TITLE
Slicing syntax on histogram differs from numpy

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#355]
Let's say I have a histogram with three axes and I want to rebin the second.
```
h[:, ::bh.rebin(2), :] # ok
h[:, ::bh.rebin(2)] # fails
```
The second version should also work, but it complains that the number of tuple elements is not equal to the number of axes.

**Comment by henryiii** [comment]
You can explicitly do it: `h[:, ::bh.rebin(2), ...]`. Numpy's syntax predates `...`, and Numpy has the idea that `a[1][2] == a[1,2]` which we don't. I think it's better to require explicit indexing. If you allow auto "..." at the end, it becomes less clear and explicit.

**Comment by HDembinski** [comment]
I know that I can do it, but I think the `...` is not helping clarity and just costs typing.

**Comment by HDembinski** [comment]
And it differs from numpy syntax, so it is inconsistent.

**Comment by henryiii** [comment]
`h[:, ::bh.rebin(2), :]` is much clearer; I now know you have a 3D histogram. If you have too many axis, you can use `...`. Even better, you should do `h[{1: <slice/selection> }]`. I think this is a historical issue Numpy has that we can avoid.

**Comment by henryiii** [comment]
If you really feel strongly about it, we can do it. Most of the mistakes I've seen students make on numpy's broadcasting are due to the fact it adds dimensions as needed rather than being explicit. It's a case where they dropped the "explicit is better than implicit" due to a language issue that is no longer relevant (`...` didn't exist).

It would also allow people to use `h[1][2][3]`, which is not a big deal in Numpy (no copies are made) but is a big deal for us, we make a new histogram each time. I think we should try to encourage users to do the right thing by making it hard to do the wrong thing.

**Comment by henryiii** [comment]
We could instead improve the error message so that it's clearer what to do or change.

**Comment by HDembinski** [comment]
I still feel strongly that `h[:, ::bh.rebin(2)]` should work as much as `h[:, ::bh.rebin(2), :]`. I don't see how the insistence of adding `,:` is making the call more safe. We should still raise an exception when too many `,:` are passed, but not if some are missing at the end.

I am surprised that you value deviating from numpy here more than consistency with numpy.

I understand the point about `h[1][2][3]`, but it is unrelated to my point, no?

**Comment by henryiii** [comment]
If you add the ability to drop items in the `[]`, you can write `h[1][2][3]`, and it will work, it will just be very slow compared to `h[1,2,3]` - that comes along with allowing missing `:` to be added at the end. Also `h[::bh:sum][::bh:sum]` will start working but is less than ideal. Also this only works one direction, you can't do the other direction - while you can in Numpy, since in numpy transposes are a 0-copy operation. The "encourage users to do the right thing by making it hard to do the wrong thing" was from you.

You can always add something, but you can't remove it easily. This will make it less safe and we can't go back.

The design was to be 100% okay with something working in numpy and failing on histograms, or working on histograms and failing on numpy; we just do not allow something to work both in numpy and histograms, but produce different results. This nicely fails if you forget the extra `:`, and there's a way to make it work on both if you are more explicit.

**Comment by HDembinski** [comment]
How about allowing `h[1, ...]` but not `h[1]`?

**Comment by henryiii** [comment]
> How about allowing `h[1, ...]` but not `h[1]`?

I think that's exactly what we do now?

I think if we do allow histogram views, so that h[1] doesn't make a copy, that's when we should remove the requirement that this must be explicit (using an Ellipsis is considered explicit). I'm fully in favor of supporting histogram views, but it's not likely to be added soon (2.0?).

**Comment by HDembinski** [comment]
Yes, you are right.
