### ISSUE TITLE
Add shortcut: Boolean / Binary axis

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#364]
Due to the fact that boost-histogram has to be able to convert axes from Boost.Histogram, you have to have a 1:1 correspondence between Boost.Histogram axes and boost-histogram axes. So Bool axes can not be a true class that would persist and be completely unique. This also is true with the cast feature - you can convert a boost-histogram to a boost-histogram.cpp or hist, but it passes through the C++ type and would loose the distinction between Integer and Bool.

So we have two possible spellings for the "bB"ool axis type. The spelling `bool`, which would highlight it as a function and a shortcut, and `Bool`, which would hide that fact, but might surprise a user down the road. You could make Boost a class that generate Integer axes, though, and type checks as an Integer axes (it would be a subclass with an overridden `__new__`).

One third option: Bool could be a special case for *all* `Integer(0, 2, underflow=False, overflow=False)` axes; if you slice or otherwise regenerate the axes, if any Integer axes matching Bool are found, they are called Bool. Since Bool would be a subclass of Integer, it would not break things to be called Bool. I think that's actually the least surprising, actually, though not sure how well it generalizes if we have other shortcuts.

@HDembinski, thoughts?

**Comment by HDembinski** [comment]
The axis should be called Binary, not Bool, to follow the existing pattern.

**Comment by HDembinski** [comment]
It is not clear from your description, but I think you talk about Python implementations. I think we should add a Binary axis in C++ and wrap that just like the other axes.

**Comment by HDembinski** [comment]
Making new axis types in C++ is easy, as you know.

**Comment by HDembinski** [comment]
I can add one over the weekend. A dedicated binary axis has no state compared to an integer axis.

Considering the name, "binary" or "boolean"? Either one is fine, but not "bool" or "Bool"

**Comment by henryiii** [comment]
Is there a benefit to a true boolean/binary axis? Adding an axes to the variant causes the compile memory usage, time, and size to grow; it's it's really identical to a specific Integer axis, it would be nice to reuse that one. Another idea is we could add an identifier integer to the metadata in C++ that we could internally use for "variants" of an axis type. Integer vs. Boolean, for example, and this would extend if we had other shortcuts (I'm 99% you've mentioned at least one more possible shortcut).

**Comment by HDembinski** [comment]
> Is there a benefit to a true boolean/binary axis?

It hard to say whether there is a benefit in practice. The theoretical benefits are clear, the binary axis has no state other than the metadata and should be faster than an integer axis.

**Comment by henryiii** [comment]
You could test it and see if there's a measurable benefit - if it's less than a few percent, I think saving compile time and complexity are probably valuble. I'm thinking have a system that allows general variations on axes would be useful elsewhere down the line too, so adding a Python variant selection integer to the C++ axes metadata may be a good idea.

Do you remember your other shortcut idea? I remember you suggested two somewhere long ago, one was Boolean, but don't remember the other. Maybe it was Radius?

I don't have a strong preference for Boolean vs. Binary, by the way.

**Comment by HDembinski** [comment]
I think the other one was "Probability", no flow bins and going from 0 to 1.

I am currently implementing the axis `binary` in C++. I am undecided whether I like `binary` or `boolean` better, what do you think? Perhaps `boolean` is more consistent with `integer`.

I will add this axis anyway to C++, so boost-histogram should use it. We should keep the internal design clean and not sacrifice it for something like this. There are other ways to reduce compile time. Since most of the time is spend compiling the fill function, I will try to fix that. Trying to optimise compile-time here if it is not a bottleneck is not helpful.

I don't like this idea at all of using metadata to change how axes are displayed. That is a misuse of what metadata is supposed to do. I further think it is totally acceptable if `boolean` in boost-histogram is just a factory function that creates a suitable integer axis.

**Comment by henryiii** [comment]
Yes, it was Probability. That should be fine returning a Regular axis. So we can have `boolean` axis  as a special type, and a `probability` factory function in boost-histogram.

**Comment by HDembinski** [comment]
Ok 👍 The develop branch has the axis called "binary". I went with my original name just to get this out, but I am considering renaming to "boolean". Just to clarify, my problem with "[Bb]bool" was that I cannot have a C++ type of the same name, because classes start with lower case and bool is a builtin type.
