### ISSUE TITLE
WeightedMean accumulator should not expose `sum_of_weighted_deltas_squared`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#410]
The attribute `sum_of_weighted_deltas_squared` is part of the public interface, but it should be private. This is an implementation detail.

**Comment by henryiii** [comment]
~~This is why we have copies of the Boost.Histogram accumulators in boost-histogram. You have to expose the memory to Python in order to make a NumPy record array.~~

~~The only think that we could hide is `view.sum_of_weighted_deltas_squared`, but `view["sum_of_weighted_deltas_squared"]` would still work, and even then, we would break consistency that you can operate ~~

~~PS: I'm talking about views - I think accumulators should match the views. I haven't looked at this from the point of just removing them from the accumulators.~~

Wait a minute, I assume you just mean adding an `_`, that's easy to do and should be done.

**Comment by HDembinski** [comment]
Yes, just add `_` :)
