### ISSUE TITLE
AxesTuple.edges too deeply nested

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#412]
```py
h = bh.Histogram(bh.axis.Regular(5, 2, 10), bh.axis.Regular(2, 0, 6))
print(h.axes.edges)
```
produces
```py
[array([[ 2. ],
       [ 3.6],
       [ 5.2],
       [ 6.8],
       [ 8.4],
       [10. ]]), array([[0., 3., 6.]])]
```
I think the arrays should be 1D, not 2D. This would allow one to do, for example,
```py
pyplot.pcolormesh(*h.axes.edges, h.view().T)
```
which currently does not work.

**Comment by henryiii** [comment]
No, this *is* ND data, with NumPy broadcasting optimizations. The reason it does not work is that Matplotlib expects ij ordering instead of xy - which I think was a mistake (at least as the only input).

If you made this 1D, you would loose all ability to make vectorized calculations with this, that is

```python
X, Y = hist.axes.centers
X + 2*Y 
```

 (computes x + 2y for each element, calculations like these are used in computing a projection from a histogram to a plane, which was a lot of my Thesis work…)

```python
X, Y = hist.axes.widths
Volume = X * Y
```

This is how we compute density, etc…

The hint to the error here should be the `.T` - that’s the weird ij indexing. The correct way to do this is:

```python
plt.pcolormesh(h.axes.edges[0].T, h.axes.edges[1].T, h.view().T)
```

This works as it should, since now you’ve fixed the indexing issue - the 2D data wasn’t the problem. We could add a specialized tuple here too, though, and allow:

```python
plt.pcolormesh(*h.axes.edges.T, h.view().T)
```

Or something else like `.ij.centers` and/or `.flat.centers`, etc.

Making this 1D is also more error prone:

```python
plt.pcolormesh(h.axes.edges[1].flatten(), h.axes.edges[0].flatten(), h.view().T)
```

Is a clear mistake, but it works if the axes have the same dimensions. While

```python
plt.pcolormesh(h.axes.edges[1].T, h.axes.edges[0].T, h.view().T)
```

Breaks, like it should, even if the axes are the same dimensions, since it detects the shape issue.


There are, however, some possible fixes from the Matplotlib side. One is that they could add an argument to allow xy indexing - then this would become:
plt.pcolormesh(*h.axes.edges, h, order=“xy”) # you don’t even need the .view() now!

FYI, we discussed this in detail about a year ago, and there's a Matplotlib issue were I discussed it with the devs.

**Comment by henryiii** [comment]
FYI, an even better example, a common mistake:

```python
plt.pcolormesh(*h.axes.edges, h.view())
```

will always fail if the dimensionality of `h.axes.edges` matches `h.view()`. If these are 1D, it will *not fail if the histogram is square*, but produce an incorrect plot (since you are mixing giving it xy indexing but it can't tell you've made a mistake, since your are using the 1D shortcut instead of the correct 2D input, and will assume ij indexing. Due to broadcasting, matplotlib is actually smart enough to tell you are wrong.

It's really hard to tell the plot is reversed, since the labels look correct, just the data is inverted. The current design avoids this ever happening.

**Comment by HDembinski** [comment]
The current design avoids me using `h.axes.edges`. What I do is this
```
plt.pcolormesh(h.axes[0].edges, h.axes[1].edges, h.view().T)
```

I think you chose a solution that was way overthinking the issue. We want to optimise the interface not for an obscure use case, but for the common use case. There are not many people who are going to compute stuff like `X, Y = hist.axes.centers; X + 2 * Y`. I never had to compute that. In statistics, if you use the bin centers for anything else than plotting, you are doing it wrong. Statistical models need to me integrated over bin edges. You can always restore the dimensions for these obscure use cases from simpler data structures.

The alternatives you wrote are too complicated and require even more typing. This is unintuitive:
```
plt.pcolormesh(h.axes.edges[1].ravel(), h.axes.edges[0].ravel(), h.view().T)
```
And this as well
```
plt.pcolormesh(h.axes.edges[1].T, h.axes.edges[0].T, h.view().T)
```

The best suggestion you gave is:
```
plt.pcolormesh(*h.axes.edges.T, h.view().T)
```
The matplotlib indexing is not weird, just attuned to a different convention for image data, where they put the origin at the top left instead of the bottom left.

I do admit that your system is logical, just not really obvious unless your name is Henry Schreiner.

Then let's please add `.T` at some point, so that I can write the last version.

**Comment by henryiii** [comment]
> Then let's please add .T at some point, so that I can write the last version.

I have a PR for it. #414  Do you want to try to push a small release before Friday, so you can use this in the talk? I could also change the names of the private items on that time scale #410 and #411. We could add a line at the bottom with the important ones, too; writing custom reprs for ndarray is really tricky - due to all the customization they have, it's either all or nothing IIRC.

**Comment by andrzejnovak** [comment]
I still haven't had the time to get properly acquainted with bh, so I may be out of my depth, but I too would expect `h.axes.edges` to return a list of 1D edge arrays. Is there any use-case to keep this "jagged" format (I can only think of outer product, but unsure what it would be good for)? Apart from the `pcolormesh` compatibility issue, this format would kind of explode if you have more axes.

Given the difference in "2d histogram" for `numpy` and `matplotlib`  maybe it would be helpful to have a `to_mpl()` method along `.to_numpy()` so that user wouldn't have to worry about putting `.T` in semi-random places.

**Comment by henryiii** [comment]
X and Y are conceptually always 2D arrays, see the MPL [pcolormesh documentation](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.pcolormesh.html):

> X, Yarray-like, optional
> The coordinates of the quadrilateral corners. The quadrilateral for C[i, j] has corners at:
> 
>  ```
> (X[i+1, j], Y[i+1, j])           (X[i+1, j+1], Y[i+1, j+1])
>                       +---------+
>                       | C[i, j] |
>                       +---------+
>     (X[i, j], Y[i, j])           (X[i, j+1], Y[i, j+1])
> ```
> 
> Note that the column index corresponds to the x-coordinate, and the row index > corresponds to y. For details, see the Notes section below.
> 
> The dimensions of X and Y should be one greater than those of C. Alternatively, > X, Y and C may have equal dimensions, in which case the last row and column of C will be ignored.
> 
> **If X and/or Y are 1-D arrays or column vectors they will be expanded as needed into the appropriate 2-D arrays, making a rectangular grid.**

Emphasis mine.

In the future, if we were to add a non-retangular axes pair, like hexagonal binning, the edges array is not decomposable via broadcasting rules, and you have to have a 2D output array. The current design would support that. Making them 1D arrays would not. (Now, future work would be need to be done for the axes internally, but the API here supports it)

As a shortcut, 1D arrays are expand into 2D for you. But the data naturally is 2D, just like `h.axes.widths` and `h.axes.centers`.

Instead of trying to work around ij indexing in matplotlib (inherited from Matlab, by the way) , we should come up with a protocol for communicating histograms to plotting libraries, and then try to get matplotlib to support it. I've been working on a draft; I could post it in an issue.

And, if you really don't like the shortcut, just don't use it!

```python
1D_axes = [x.edges for ax in h.axes]
```

Now you have a list of 1D axes arrays. Building the grid is harder, as you have to make sure the indexing matches `.view()` - while the shortcut does that for you.

The #414 PR also allows `h.axes.edges.flatten()` as well, so you can get your 1D arrays that way.

**Comment by henryiii** [comment]
With the current PR, this is what common uses would look like:

```python
plt.pcolormesh(*h.axes.edges, h.view()) # Error, not ij indexing
plt.pcolormesh(*h.axes.edges.T, h.view().T) # Works
```

If we made this 1D instead:

```python
plt.pcolormesh(*h.axes.edges, h.view()) # Error if not square,
                                        # but works, with *incorrect plot* plot square!
plt.pcolormesh(*h.axes.edges.T, h.view().T) # Works
```

So this is less powerful and error prone.

**Comment by henryiii** [comment]
Just curious, what would your `.to_mpl()` method return?

**Comment by andrzejnovak** [comment]
I understand not wanting to change the output if it will conflict with something else (now or in future). It makes more sense now to me with complementary `h.axes.width` and `h.axes.centers` which are naturally 2d (I didn't know this) and having that internally consistent is more important than the outside convenience of fetching edges as 1D arrays. Though I still have trouble imagining what use-case would be simplified by the 2D form of `h.axes.edges`.

`.to_mpl()` would return `H, X, Y` correctly transposed to be able to run 
```
plt.pcolormesh(hist.to_mpl())
```
which really seems to be root of this issue.

**Comment by henryiii** [comment]
I assume you mean:

```python
plt.pcolormesh(*hist.to_mpl())
```

But what if someone wants to use `imshow`? Or some other api call? Contour does use this API, IIRC.

Also, the edge arrays are naturally 2D too; even the mpl docs say the 1D arrays will be converted to 2D as a shortcut.

**Comment by andrzejnovak** [comment]
Right, thanks for the correction :) You are right about contour as it takes same sized arrays (bin centers vs edges). OTOH I'd argue there's only one appropriate method to 2d hist plotting in mpl and that's `pcolormesh` (`pcolor` is essentially the same). `imshow` is geared towards sth else entirely.

**Comment by henryiii** [comment]
I think we should not have or hold off on an explicit `to_mpl()` function, at least until Matplotlib 4.0. One of the the projects they are working on is enabling customizations for this sort of thing. Hopefully, if that goes well, then we can use the API they are developing to allow histograms to plot natively in MPL 4 without having to break it up into parts.

Checking around with other plotting libraries, mayavi does not have a 1D shortcut AFAICT, all arrays must be 2D (or 3D for the 3D plotting functions). As far as [I can tell](https://docs.bokeh.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure.hexbin), bokeh only does hexagonal binning (very pretty, but that's the only choice ?!?!?) and images. Plotly seems to support the 1D shortcut.

**Comment by HDembinski** [comment]
> > Then let's please add .T at some point, so that I can write the last version.
> 
> I have a PR for it. #414 Do you want to try to push a small release before Friday, so you can use this in the talk? I could also change the names of the private items on that time scale #410 and #411. We could add a line at the bottom with the important ones, too; writing custom reprs for ndarray is really tricky - due to all the customization they have, it's either all or nothing IIRC.

As you prefer, we could make a quick release with this. Maybe you want to include it in your part of the talk? It is your work, and I think it may fit better in part 1.

> I could also change the names of the private items on that time scale #410 and #411

I chose not not mentioned those attributes in my talk, so if we can hide them before the talk, that would be great, but it is not necessary.

**Comment by HDembinski** [comment]
> I think we should not have or hold off on an explicit to_mpl()

Agreed.
