### ISSUE TITLE
DRAFT: Plotting (and later fitting) Protocol

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#423]
I'm working on defining a Protocol for plotting histograms. To do so, I need some way to access the values and optionally variances so that mplhep and others can decide on what to plot. Here is one possible suggestion:

```python
from numpy.typing import ArrayLike # requires NumPy master
from typing import Protocol, Optional, Tuple, Union, Iterable

class PlottableAxis(Protocol):
    label: str # May be removed soon

    edges: ArrayLike

     # For non-categorical axes, this returns None
    categories: Union[Iterable[int], Iterable[str], None]

class PlottableHistogram(Protocol):
    axes : Tuple[PlottableAxis]
   
    # Values returns the array or the values array for specialized accumulators
    def values(self, flow=False) -> ArrayLike: ...

    # Variance returns the variance if applicable, otherwise None
    # If counts is none, variance returns NaN for that cell (mean storages)
    def variances(self, flow=False) -> Optional[ArrayLike]: ...
```

We can look at labeling in a later draft, but there are a few key points:

* `.values()` is like `view()` for simple storages, and like `.view().value` for complex ones, providing plotting libraries a consistent way to access the central values for plots.
* `.variances()` returns None if a storage does not provide information for variances, allowing a plotting library to use `if variances := h.variances():` to skip plotting error bars, or do something reasonable. If it exists for that storage, it returns an array.
* `.axes[I].categories` is an array of labels if this is a Category storage, otherwise it is None.

I didn't add `.counts()`, but maybe that should be included too?

@HDembinski, what do you think?

This is assuming the master object *is* the API. You could also have a `__histogram_dict__` that returns something like what you see above - then it's much easier to add to existing libraries like Physt and doesn't affect/change the public API, but on the flip side, it's duplicated, all or nothing, and doesn't provide API consistency for users. (Double underscores for clarity - you really aren't supposed to add anything with double underscores, so for an API choice, it might not be ideal).

PS: This is post 0.10.0, possibly post 1.0, so no rush here, feel free to come up with something better.

PPS: Initially, boost-histogram and Uproot4 would implement this, and Hist would get it for free since it is a boost-histogram.

**Comment by henryiii** [comment]
Mostly from here, for reference: https://github.com/scikit-hep/hist/issues/64

**Comment by henryiii** [comment]
I should include @jpivarski since I'm including Uproot4 here.

**Comment by HDembinski** [comment]
Does this mean you want to add `.value()` and `.variance()` to boost-histograms?

Comment on uniform handling of heterogeneous types:

a) By enforcing the same interface on all types
b) By making a view, which takes the original type and adds the missing interface that is not available
c) By using free functions (e.g. `get_categories(...)`, `get_values(...)`)

a) is the simplest and most straight-forward. It is the easiest to comprehend for a user. So this is good if you want to offer users a consistent interface, even though it is disputable whether adding methods/attributes that return None makes sense in all cases.

b) and c) are good for library developers. In C++ Boost Histogram, I chose approach c). If I would do it again, I would probably use b).

**Comment by HDembinski** [comment]
> I didn't add .counts(), but maybe that should be included too?

I think it is not essential. I use .counts() in practice to mask bins in profiles which have no entries. This would not be needed if there was a convention that .value() and .variance() returns NaN when there are no entries.

**Comment by henryiii** [comment]
Currently, following what I have above would amount to the following changes to boost-histogram:

* `.values()` and `.variances()` added to histograms - we could instead switch to using `to_numpy` as mplhep does not, but I think this would be cleaner this way. I'm open though. (@andrzejnovak could weigh in too)
* `.categories()` added to axes, returns None if not categorical, the categories otherwise, so plotting would be able to tell that category labels are needed.
* `.label` added to axes (see #430 ) - otherwise, labels can't be attached or propagated along through transformations and such.

I didn't include a way to get circular status for histograms, which plotting would ideally have - I think we could just formalize what we already have implemented, `.options` with circular there. If we did that, we could include underflow/overflow status (growth shouldn't matter for plotting, so would not be formalized here). I'll try to add this later.

Uproot TH* would also want to implement the above API too.

**Comment by HDembinski** [comment]
> I think it is not essential. I use .counts() in practice to mask bins in profiles which have no entries. This would not be needed if there was a convention that .variance() returns NaN when there are no entries.

Actually, now I remember, since variance is the variance of the samples, you need the counts() if you want to compute the error on the mean.

**Comment by HDembinski** [comment]
> .values() and .variances()

As mentioned elsewhere, singular forms are preferred over plural forms unless required for consistency with existing code.

>     def values(self, flow=False) -> ArrayLike: ...

Since most histogram libraries don't know anything about `flow`, you may want to make these properties.

**Comment by andrzejnovak** [comment]
I would not get hung up on what `to_numpy()` methods do. They should stay and do just what you expect them to, return a numpy-like histogram tuple w/o uncertainties. Having all the methods take `...(flow=True)` also makes sense, though in reality this would be ignored for vast majority of plots.

re `variances()` I think it may be a bit of an unfortunate misnomer inherited from the TH1 method. I expect what we actually want is the sumw2 info to go into something like this: https://github.com/scikit-hep/mplhep/blob/master/mplhep/plot.py#L214-L221 It already caused some confusion on a pervious mplhep issue.

**Comment by henryiii** [comment]
> you may want to make these properties

I think for consistency, making these function calls what support flows is best in boost-histogram. Histograms support `flow=` arguments on methods, and axis do not and use properties instead (as, really, only edges would make sense - centers and widths can't include flow). However, we could leave it out of the plotting Protocol if there's no reason to make it generally plottable - then someone defining `def values(self):`  would still be a valid plottable histogram. Variance is also computed in some cases, so while one would expect to be able to write `h.variances = ...`, it is more obvious that `.variances()` is not directly settable.

On an unrelated note, I think our choices so far have also been orthogonal to Physt - @janpipek could comment, but I think these could be, in theory, added to Physt histograms to make them plottable under the same Protocol.

**Comment by janpipek** [comment]
Hi,

thanks for including me in the conversation. You're doing a great job!

I am currently not going forward with physt at a statistically significant pace ;-) Too much work and too small user base to make the development a priority...

I am split between a) adding new features, b) major API redesign, c) porting some high-level stuff to boost-histogram and freezing the library for the moment. Adapting to the protocol would not be a problem in either case (a few aliases to "a", good naming schema to start with for "b"). 

Just to give my two cents:
- The `flow` argument name sounds a bit cryptic (I had to look in the docs to understand that it is actually a suffix for under-/over-), perhaps too strict to be required by all libraries / histograms (btw. how do you define and treat underflows in case of multidimensional histograms?)
- I would warn against making `to_numpy` part of the protocol, unless the numpy compatibility is essential part not just of the implementation, but also of the API (for the coming years).
- Why singular, as in `variance` and `value`? 
- That `variance(s)` may be or may not be actual variances in the statistical sense, is a good point (sumw2 is a bit cryptic but at least semantically correct). Even the assumption that entries are drawn independently from some distribution, may not be valid for many uses of the library (although then even `sumw2` is a debatable thing). But anyway, physt has the same problem (even worse: errors) ;-)

In any case, I will follow the issue and will happily make physt compatible :-)

**Comment by HDembinski** [comment]
I agree with the @janpipek that flow should not be exposed by a generic API.

I am ok with adding .values() and .variances() to the histogram class itself as a crude lossy generic way to access data without going through .view(), but these should only allow access without flow.

I am against adding .categories to Axis objects. It would be None for most axis types. I don't think the generic API should support category axes at this time.

**Comment by HDembinski** [comment]
The API does not support circular axes, which seems a more important flaw, because a plotting tool may want to draw a histogram with a circular axis differently. We could easily add .circular to each axis object to query this.

**Comment by HDembinski** [comment]
The other point against .categories is how redundant and confusing that would be for a category axis, which already acts like a tuple of items, and then on top it would have an attribute to access the very same information.

**Comment by HDembinski** [comment]
I suggest to add .discrete to Axis types, which is True or False. If this is true, it is a category-like axis (Integer, Boolean or ...Category)

**Comment by HDembinski** [comment]
PlottableAxis needs `__getitem__` to access categories if discrete or pairs of bin edges if not discrete.

**Comment by HDembinski** [comment]
What should .variance() return for each Accumulator? The answer is only clear for Weight().

Double(): None or sqrt(values)?
Mean(), WeightedMean(): Variance of the mean or Variance in the bin?

There is a right answer and that is why I am not happy with this generic API that hides essential details.

**Comment by HDembinski** [comment]
Another flaw: `.edges` is not a generic API and should be removed. `.edges` is restricted to axes without gaps, in other words, all consecutive bins share an edge. That does not generally have to be the case, especially when you start to mask out parts of a histogram. A generic API uses `__getitem__` and returns intervals for continuous and values for discrete axes. We are not concerned with maximum efficiency of transferring data here

**Comment by jpivarski** [comment]
> Another flaw: `.edges` is not a generic API and should be removed from the protocol. `.edges` is restricted to axes without gaps, in other words, all consecutive bins share an edge. That does not generally have to be the case, especially when you start to mask out parts of a histogram.

For Awkward lists, this is the distinction between offsets (in [ListOffsetArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListOffsetArray.html)) and starts/stops (in [ListArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListArray.html)). The latter is more generic, but the former is common enough to get its own name. (Apache Arrow, for instance, only has offsets, no starts/stops.) In histogramming, the offsets are usually called "edges." I don't think we have a histogram-specific word for starts/stops: maybe "edge_starts" and "edge_stops"?

(The use of "start" and "stop" rather than "beginning" or "end" is deliberately copying Python's use in ranges, where there is a well-established convention that "start" is inclusive and "stop" is exclusive. The words "begin" and "end" are more often used in program control flow, especially "end" (i.e. Lua)).

There are a few ways this could be dealt with:

   * If gaps are the only possibility and not overlaps, then you could represent the starts/stops as an offsets with the gap as an additional bin, either filled with `0` or `NaN` (depending on whether you want to make the distinction between "we looked and didn't find any entries there" and "we didn't look"). However, this would no longer be a view: you'd have to modify the edges _and_ the bins before returning them.
   * If you allow overlaps, then you'd just have to return the full starts/stops, anyway. But whereas overlaps make very little sense in Awkward lists, they make no sense for histograms: if you have two bins that overlap parts of the same domain, does an entry fill both of them? A normalized histogram would have a sum of bins greater than 1! (Though gaps can make the normalized histogram have a sum less than 1, so maybe that's not too strange.)
   * If you're going to be presenting offsets _or_ starts/stops, how about if the former are always 1-dimensional with length `number_of_bins + 1` and the latter are always 2-dimensional with shape `(number_of_bins, 2)`? All numerical axes can have the starts/stops interface, whether they have gaps or not, but only non-gap, non-overlapping axes can have the offsets interface. However, most histograms people use fall into the latter category.

Note that it's hard to get a 1-dimensional offsets from a 2-dimensional starts/stops. You'd have to

```python
assert numpy.array_equal(startsstops[1:, 0], startsstops[:-1, 1])
return numpy.append(startsstops[:, 0], startsstops[-1, 1])
```

**Comment by henryiii** [comment]
Here's my next iteration of the Protocol, based on @HDembinski's suggestions, with one addition that should address the last concern: I've added `.counts()`; if that is None, then this is a "normal" histogram and not a Profile. This way, plotters can either have specialized handling for mean plots, or they can require that `.counts() is None` if they do not support them. I don't see any reasonable way that the variance of the counts would be plotted, so there's no way to access that in the protocol for now. I've also left off `flow=True`, though @nsmith- wanted that for plotting - he can argue why it should be included (but that could be later; we also need to think about fitters and such). We can also include things not in the protocol, we just can't use them in mplhep, etc. For example, boost-histogram will have `flow=False` arguments for consistency with all other methods on histograms, even if they are not usable by mplhep, etc.

```python
# from numpy.typing import ArrayLike # requires unreleased NumPy 1.20
from typing import Protocol, Optional, Tuple, Union, Iterable, Any

ArrayLike = Any

class PlottableAxis(Protocol):
    # label: str - Optional, not part of Protocol

    # True if the axis "wraps around"
    circular: bool

    # True if each bin is discrete - Integer, Boolean, or Category, for example
    discrete: bool

    # Get the pair of edges (not discrete) or bin label (discrete)
    def __getitem__(self, index: int) -> Union[Tuple[float, float], int, str] : ...

    # Return the number of bins (not counting flow bins, which are ignored for
    # this Protocol currently)
    def __len__(self) -> int: ...

class PlottableHistogram(Protocol):
    axes : Tuple[PlottableAxis]
   
    # Values returns the array or the values array for specialized accumulators
    # All methods can have a flow=False argument - not part of Protocol
    def values(self) -> ArrayLike: ...

    # Variance returns the variance if applicable, otherwise None
    # If counts is none, variance returns NaN for that cell (mean storages)
    def variances(self) -> Optional[ArrayLike]: ...

    # Count returns the number of values in a mean accumulator (also known as a
    # Profile histogram), or is None for normal storages.
    def counts(self) -> Optional[ArrayLike]: ...


# Using the protocol:
# 
# Plotters should see if .counts() is None - if not, this is a Profile then
# check .variances; if not None, this storage holds variance information and
# error bars should be included. If it is None, then a plotter can avoid
# showing error bars (recommended), or use np.sqrt(h.values()).
```

Currently sits here: https://github.com/henryiii/uhi/blob/master/uhi/typing/plottable.py 

Thoughts? Further modifications?

**Comment by jpivarski** [comment]
For scikit-hep/uproot4#167, my interpretation of the above is that Uproot histograms will do the following, which satisfies the above protocol and a little more.

   1. The main histogram will have an `axes` property to get axis objects as a tuple and an `axis(n)` method that takes `0`, `1`, `2`, `-1`, `-2`, `-3` like a NumPy axis and `"x"`, `"y"`, `"z"` because this is the naming convention in ROOT. The argument to the `axis` method is optional for 1-dimensional histograms only. I would _prefer_ only the method access, but also having an `axes` tuple is not a problem.
   2. This axis object will have `circular` (always False) and `discrete` (True if the histogram has `fLabels`, False otherwise), `__getitem__` and `__len__`, which ignore flow bins, and `__getitem__` returns a `(float, float)` or `str`, depending on whether the histogram has `fLabels` (also ignoring flow bins: `0` is the first non-flow bin). This is the minimum to satisfy the protocol.
   3. The axis object will also have `labels() -> Optional[List[str]]`, which returns None if `fLabels` are not present, and `edges(flow=False) -> ArrayLike[float]`, whose length is 1 greater than `__len__` when `flow=False` and 3 greater than `__len__` when `flow=True`. The `edges` are never None because ROOT histograms have continuous dimensions even when covered up by labels. (Some users will need to get at the data underlying this hack.) When `flow=True`, these _arrays_ will have the underflow in the first bin and overflow in the last bin, which changes the indexing.
   4. The main histogram will have `values(flow=False) -> ArrayLike`, which returns either bin counts or sums of weights, depending on `fSumw2`. Passing `flow=True` adds two bins per dimension, in a way that matches with the axis.
   5. The histogram will also have `variances(flow=False) -> Optional[ArrayLike]`, which returns None for non-profiles without `fSumw2` and variances derived from `fSumw2` otherwise. In addition, there will be an `errors(flow=False)` method with the same interface, differing only in that it takes a square root.
   6. If it's a profile histogram, I guess `counts` is the "effective entries"?

I think that `counts` might be a bad choice of words if you meant, "effective entries," something that only profile plots have. Specifically, these values (the URL in the first line points to ROOT's calculation of the same quantity):

https://github.com/scikit-hep/uproot4/blob/28d6dd5d679960bdafb18813b7b75368c2c780d2/uproot4/behaviors/TProfile.py#L21-L37

Since this formula [goes all the way back to HBOOK](http://cds.cern.ch/record/2296378/files/hbook.pdf) (search for "CALL HBPROF") and the terminology for this term in the formula [has been set by ROOT](https://root.cern.ch/doc/master/classTProfile.html#a06f2d95794b9883b976708bf08b6e421), why not call it `effective_entries` instead of `counts`? Otherwise, everything would be the same.

The word "counts" sounds like unweighted number of entries in a non-profile histogram.

One more request for clarification: variances can fail to exist for two different reasons, (1) the accumulator has no weights (no `fSumw2`) and (2) the accumulator is not profile-like. Is `variances` None in one case and full of `NaN` values in the other? What if it's None in both cases? The plotter shouldn't draw them in either case.

**Comment by nsmith-** [comment]
I think `flow` is quite important to be able to plot easily, as it is a very fast way of finding issues or (possibly pleasant) surprises in the data. I don't see a way to slice a boost histogram to make a previously overflow bin visible, so there should be some way other than `.view()` to see the contents, no?
Regarding `counts`/`effective_entries`, I guess its an estimate assuming all weights are equal (up to sign) in the case of root histograms, so including an interface for more advanced accumulators that store the actual number of entries is useful.
For fun, since axis has getitem and len, can we make it a `Sequence`?

**Comment by henryiii** [comment]
1. Yes, hist will have a way to get axes objects using axes names, for example. I would just use `axes[-2]` and `axes["x"]` instead of a separate method, though. I will modify the above to clarify it is a `Sequence`.
2. Yes, though I might add that `__getitem__` doesn't have to ignore flow bins; just `0` to `len-1` need to return the non-flowbin values. You can always do more than the Protocol, you just can't do less.
3. Feel free to add `labels` and `edges`, you can always do more. boost-histogram already has edges.
4. Yes, boost-histogram will do this too.
5. That can be done.
6. That was the idea.

I'm fine with a different name for `.counts()`, personally.

If `effective_entries()` is None, then it is not profile like, so you can differentiate using that.

**Comment by henryiii** [comment]
@nsmith- How would you propose to plot an overflow bin?

**Comment by jpivarski** [comment]
> For fun, since axis has getitem and len, can we make it a `Sequence`?

That sort of thing is too dangerous to do for fun! Awkward Arrays used to be Sequences, but along with that came `__contains__`, `index`, and `count`, which all assume that the objects in the sequence have `__eq__` defined. I had to scale it back because of unwanted consequences. Now it's just an `Iterable` `Sized` collection:

https://github.com/scikit-hep/awkward-1.0/blob/20879826b34db601276a900171305c44ec11d926/src/awkward1/highlevel.py#L39-L43

which is to say that it has `__iter__` and `__len__`, though that says nothing of the fact that it has a `__getitem__`.

But everything that comes from `PlottableAxis.__getitem__` has an `__eq__`, so maybe. I'm just saying you want to think twice about _requiring_ everything that satisfies the protocol to have all of Sequence's mixin methods.

**Comment by nsmith-** [comment]
Re: overflow bin
Well the usual way is to just add another bin to the end with the same or similar width to preceding ones. For example: https://atlas.cern/sites/atlas-public.web.cern.ch/files/field/image/monojets.png
Sometimes people manage to relabel the last axis tick with `\infty`. Sometimes people make the bin wide enough to just contain the max observed value, which has the advantage that you can still create an accurate bin-width-normalized plot, although often ends up looking rather ugly.
But MET searches aside, there is a certain utility to just checking something is there even if it is not the way you plan on presenting it in publications.

**Comment by jpivarski** [comment]
With the protocol not specifying a `flow` option, it also doesn't need to specify whether the underflow and overflow come are to the left or right of the main bins. If plotters really are drawing underflow and overflow, they'll not only need to know the spelling of "`flow`", but also where to look for them in the values.

I've never tried this, but I've often thought that overflow bins should be visualized with an exponential tail in the `(‒∞, low]` and `[high, ∞)` parts of the plot. The magnitude in that bin should be equal to the number of underflows/overflows. I think the shape of the exponential curve in that bin is underconstrained: there's height and expectation value subject to an area constraint, but the expectation value can be set to the average bin width or something.

There's a more prosaic way for plotters to display this information: [in the legend](https://community.linuxmint.com/software/view/mn-fit).

**Comment by henryiii** [comment]
What do you think about the restructuring here: https://github.com/henryiii/uhi/pull/1 ? This would be in line with how boost-histogram already presents "circular", and would make it easier to add `options.underflow`, `options.overflow` to the protocol if we want to support flow bins (which would allow you to tell underflow on, overflow off from overflow on, underflow off).

**Comment by jpivarski** [comment]
In what direction is this information flowing? The histogram has to tell me whether it's circular or discrete, and maybe whether flow bins exist, but I tell the histogram whether I want them to appear in the edges, values, and variances, right?

**Comment by henryiii** [comment]
> it also doesn't need to specify whether the underflow and overflow come are to the left or right of the main bins

This is only a problem for the axes, since the returned array is "normal" if you pass `flow=True`. The reason for the odd ordering was to make an array act like "flow=False" but secretly containing flow bins - except it fails in corner cases like trying to use Python's negative indexing to do normal operations, calling .size, etc. So the only problem would be in the axes object, where you can't pass a keyword; but that's okay, as long as you can query `options.underflow` and `options.overflow`.

Once we decide the commit above, I can make a PR that would show what adding flow to the Protocol would look like.

**Comment by henryiii** [comment]
> In what direction is this information flowing? The histogram has to tell me whether it's circular or discrete, and maybe whether flow bins exist, but I tell the histogram whether I want them to appear in the edges, values, and variances, right?

You can ask for `flow=True` for the data (not in the current protocol, just as an extension currently), otherwise, everything is flowing from the histogram - this doesn't define how to make one, just what is present so plotters can plot them.

If we did add the flow keyword argument to the Protocol, then libraries would have to implement a flow keyword, but they would not have to support flow histograms - `options.overflow` and `options.underflow` would just always return False. The flow keyword would be a no-op in that case, since a histogram without flow returns the exact same thing with `flow=True` - that just says "add overflow and/or underflow bins if you have them", or more accurately for boost-histogram, "don't truncate any flow bins".

**Comment by jpivarski** [comment]
It matters for the order of edges in the axes and the order of bins in the `values` and `variances`. There seems to be enough momentum behind what you call the "normal" order to specify it, if a `flow` option is added to the protocol.

As for querying, is your current proposal to add `flow: bool` to `values`, `variances`, `effective_entries`, and presumably an `edges` in the PlotableAxis that puts the underflow bin first and overflow bin last?

The `options.overflow` and `options.underflow` come _from_ the histogram, so what do they represent? Are they booleans representing the existence of flow bins, if I happen to ask for them with `flow=True`, thus telling me whether `flow=True` is a no-op?

**Comment by andrzejnovak** [comment]
It's not so much if a library does or does not implement flow, but if it does then how. If it's not in the protocol any library can decide on its own implementation and they might not match up, which is confusing. Take the current situation where coffea.hist, uproot.TH1 and uproot4.TH1 are all dealing with flow differently.

**Comment by HDembinski** [comment]
@jpivarski regarding using an exponential tail to represent flow content: that is really bad. One cannot and should not assume anything about a distribution that was not observed.

Regarding .counts(). You need this and it is correctly named. When you make a profile, the variance in each bin is not always what you want. Often you want the error on the mean, which is variances()/counts(). This is important, so please let me know whether I am not clear.

Regarding flow: just adding a flow keyword to .values() .variances() is a bad design, passing the same request several times is repetitive and more importantly it is error prone, because there is no automatic synchronization. When I want values with flow, I also want the corresponding bins and the corresponding variances, etc. I never want to mix flow=True and flow=False queries. The interface should reflect that.

@jpivarski using edges with len + 1 only works when your bins do not have gaps. It is not an interface that generalizes to future needs.

**Comment by henryiii** [comment]
`.counts()`: I'm fine with this name - I've changed the git version of the Protocol proposal to reflect it. I think @jpivarski was worried that users would try do use `h.counts()` on a regular histogram and get the 

Flow: It doesn't have to be in v1 of the protocol, but I should point out that this is how we already do it; .`view()`, `.to_numpy()`, etc, all have flow in boost-histogram. It would be more elegant to have a `h.flow` proxy that returned a histogram that switched the default; but this is significantly harder to grasp and follow throw the code - is your "h" a flow on or flow off histogram? If you have `flow=True` on each call, you are immediately reminded of the important fact that you are getting flow bins - if you are new to the code, you'll know something is up and you will have to go see what flow is. Here I think consistency (within boost-histogram) is key. Also, axes properties are often unrepresentable with flow on - centers and widths would be infinite, edges is the only one slightly useful (might be important with masking?).

But this is one reason we were originally leaving flow off. It's always valid to provide it (all boost-histogram methods on histograms have a flow argument, so it would be consistent to have flow for values, etc, even with it not being part of the Protocol). I'm still not sure you'd ever want flow to be "automatic" when plotting - if you are manually plotting instead of feeding a library function, sure, but then you know exactly what you have and don't need a generic interface designed for plotting libraries.

I'm just using `__getitem__` for the protocol. We already provide `.edges`, and looks like Uproot will too, but it's not part of the Protocol - a complaint plotter like mplhep should be completely general and getting the edges as an array is not necessary for that.

@HDembinski Do you like the `.options` change to the Protocol? That's closer to the current boost-histogram design, and I think it's a little more organized, at the cost of a slightly more complex Protocol. I'm fairly neutral. https://github.com/henryiii/uhi/pull/1/files 

And, @jpivarski , yes, these are boolean values that tell the plotter about the existence of those options for this axis. For example, if you had flow=True and `ax.options.underflow` was False, you'd know that the first bin is the first "edge", and not an overflow bin. They are exactly like the existing `.circular` and `.discrete` options, which is why they are bundled together.

**Comment by HDembinski** [comment]
@henryiii Your argument that I should be reminded constantly of flow is not convincing at all. I gave two strong reasons: repetitiveness and possible inonsistency against having flow keywords on several accessors. I am happy to brainstorm an alternative design, I am not sure yet what it should look like.


I was never happy with the way how it is in boost-histogram. I liked .to_numpy() despite its flaws, because it made the and the bins automatically consistent.

In fact, I am so unhappy with this issue that I suggested to take flow out of the protocol, arguing that it is not something that 99% of the plots need. And in the remaining 1% you can be bothered with manually drawing the plot.

If we want flow to be part of the protocol, we need to solve the synchronization.

One possibility is to have the protocol without flow as is on the histogram object, but have a single property, called .with_flow or just .flow which returns a shallow object that again implements the protocol but all queries include the flow bins. Such a design satisfies my requirement and histograms without flow can simply return None.

**Comment by andrzejnovak** [comment]
@HDembinski wouldn't the flow mismatch be immediately obvious if it happened? I can imagine any downstream code not complaining in that case.

> One possibility is to have the protocol without flow as is on the histogram object, but have a single property, called .with_flow or just .flow which returns a shallow object that again implements the protocol but all queries include the flow bins. Such a design satisfies my requirement and histograms without flow can simply return None.

This is a neat solution, imo not as intuitive as `flow` kwarg

> if you are manually plotting instead of feeding a library function, sure, but then you know exactly what you have and don't need a generic interface designed for plotting libraries.

@henryiii I might be missing something, but isn't it reasonable to expect that if the protocol does get put in place, it will also be used by users directly. It's always possible one will try to visualize something not available as an available method.

**Comment by henryiii** [comment]
> but have a single property, called .with_flow or just .flow which returns a shallow object

This is exactly what I meant when I said "It would be more elegant to have a `h.flow` proxy". The issue with that is that now you don't know if "h" has flow on or flow off. If you design an api, like mplhep, you might be passed a flow-on histogram. What do you do with that? I still believe there is no "general" solution for plotting a flow bin. How wide do you draw it? I think flow bins always have to be handled specifically. It's also a much more complex, less intuitive solution; the reminder that `flow=True` on every call is helpful, I think, in keeping intent clear. You are stating "I will handle flow" every time. You can always write `flow := True` and use `flow=flow` elsewhere. Using flow should be a clear opt-in and should not impede users who don't know what flow is; making it a proxy object causes "flow=True" histograms to be potentially available every time you write `def f(h): ...`.

The big issue currently is that axes properties cannot have flow; that is, `.edges` will always miss the flow bins. If it was easy to turn on `flow=True` for edges, then I don't think it would be so tempting to misuse `to_numpy`. That's part of the API you designed, by the way. :)


To be clear:

```python
values = h.values(flow=True)
variances = h.variances(flow=True)

# Or:

```python
flow = True
values = h.values(flow= flow)
variances = h.variances(flow= flow)
```

vs.

```python
# Dangerous - can pass h_f to functions
# And you still have one extra line, like example 2 above
h_f = h.flow
values = h_.fvalues()
variances = h_.fvariances()

Or
# Not any better than flow=True
values = h.flow.values()
variances = h.flow.fvariances()
```

I'm not horribly against the flow proxy idea (after all, I suggested it above), but I think it's more error prone, and requires extra checks or caution on _all_ histograms when used downstream, and is really not very common in Python, while keyword arguments are. Fitters, plotters, etc. have to be aware of it, while `flow=True` can be ignored (and likely should only be part of a fitter protocol, and not a plotting protocol).

Simple is better than complex.

**Comment by HDembinski** [comment]
> @HDembinski Do you like the .options change to the Protocol? That's closer to the current boost-histogram design, and I think it's a little more organized, at the cost of a slightly more complex Protocol. I'm fairly neutral. https://github.com/henryiii/uhi/pull/1/files

Putting the options in an .options object is probably a bit more organized, but I don't feel strongly about this. The advantage of putting the options behind .options is that they do not clutter tab completion and it is future safe against possible name clashes if we find out that there are more options to put there.

**Comment by henryiii** [comment]
For everyone following, this is done and implemented here: https://github.com/henryiii/uhi/blob/master/uhi/typing/plottable.py.

Uproot is the first package to provide support. Support in boost-histogram should follow soon (there's an in-progress PR #476 ). I'll probably help with support in mplhep unless @andrzejnovak gets to it sooner. Same goes with histoprint and @ast0815. @janpipek, you might also be interested?

I'll probably eventually expand the UHI repo to actually include a description of UHI and then propose it for a move to scikit-hep, but it's not supposed to become a dependency of something like boost-histogram, it is just a reference document, example implementation of tags, and assistant for statically checking histogram code.

**Comment by ast0815** [comment]
Is this supposed to replace the `.to_numpy()` or `.numpy()` methods? Or will this be an additional, more flexible interface for histogram objects? In any case, adding another set of methods that histoprint uses to try to get the bin edges and values out of an object should not be a problem. From reading that document, I am not really sure how it works though. An example of how to get the bin edges and bin values out of a histogram in this scheme would be useful.
