### ISSUE TITLE
[BUG] accumulators.Mean.sum_of_deltas_squared is public

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#536]
accumulators.Mean.sum_of_deltas_squared is supposed be private, since it is an implementation detail. We don't want to expose implementation details to the user.

**Comment by henryiii** [comment]
Probably should push this off to 1.1, since we'll need to verify that old Mean() histograms can be unpickled.

**Comment by henryiii** [comment]
Also, this will break uproot4, since we had to work around supporting boost_histogram < 0.12 (due to https://github.com/scikit-hep/boost-histogram/pull/475 missing). I think we can drop that now, but it needs to be done in uproot4 before boost-histogram can drop it.

https://github.com/scikit-hep/uproot4/blob/b1cf6e6b48e75dcd2e1f0c30668fb8583fe0382d/uproot/behaviors/TProfile.py#L325-L334

**Comment by henryiii** [comment]
Oops, correction, uproot uses WeightedMean, not Mean, so I think this is safe in that respect. Still need to update uproot to use #475 instead of internal details, though.
