### ISSUE TITLE
[BUG] UHI slices need to treat flow specially for unordered axes

### ISSUE THREAD

**Issue by agoose77** [scikit-hep/boost-histogram#556]
**Describe the bug**
When taking slices (as described by the UHI spec) to perform a projection, the `start` value is ignored (although must be in-range) unless a `stop` value is also provided.

**Steps to reproduce**
* [An example notebook](https://nbviewer.jupyter.org/gist/agoose77/c37032a1613986cfc3b591e45b4623af/example.ipynb)
*  [![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gist/agoose77/c37032a1613986cfc3b591e45b4623af/HEAD?filepath=example.ipynb)

**Comment by agoose77** [comment]
Closed in lieu of https://github.com/scikit-hep/boost-histogram/issues/557

**Comment by agoose77** [comment]
Upon further investigation, the issue here is when the `stop` index is calculated in `Axis._process_loc`. It seems that a value of `None` resolves to the value `len(axis)+1`. I am under the impression that the indices should be in the inclusive range[0, 2] , with -1 and 3 being the overflow bins.

In any case, this is where the `len(axis)+1` is set:
https://github.com/scikit-hep/boost-histogram/blob/c3da29978d2fb03717c754865fb32d662b91afe1/src/boost_histogram/_internal/axis.py#L175

**Comment by henryiii** [comment]
Leaving off the end gives you the overflow bin. There's no "easy" way to get the overflow bin otherwise, and when you do, say, `5::sum`, you want the sum from 5 going to infinity. That's why we have flow bins, for projections. If you want to avoid the overflow bin, you use `5:len:sum`. 

The issue with with IntCategory, not with the computation of the indices. Since the boost-histogram code does not care about the axes type, I think this might be a bug in Boost.Histogram. Using integer ranges on Categorical axes is slightly suspect, as the order doesn't have a strong meaning. [2,0,1] is also a valid IntCategory. (This should still work, but that might be related to why it's not working).

This is the commend being passed to boost-histogram for either Integer or IntCategory axes; only the former one works:

```
DEBUG:boost_histogram._internal.hist:Reduce with [reduce_command(slice_and_rebin(iaxis=0, begin=1, end=4, merge=1, mode=True))]
```

**Comment by agoose77** [comment]
After reading your comment I can see that I forgot about the `n+1` slice behaviour to include the overflow, an oversight on my part.

**Comment by henryiii** [comment]
Found the problem. Since there is no "under/over" distinction for categorical axes, the extra items "below" get added into the (over)flow bin, then get included. Boost-histogram (Python) needs special handling for categories; it probably disable all upper/lower handling when slicing with any endpoints for categorical axes.

**Comment by agoose77** [comment]
Right, so the 0th bin is the ~~over/under~~flow bin? Thanks for clarifying that, and for creating the PR.

**Comment by henryiii** [comment]
For unordered axes, the flow bin should not be viewed as just one bin; both `h[:3:sum]` and `h[3::sum]` should avoid the "flow" bin; before the patch the latter one was including the flow bin because it happens to be called the "overflow" bin. You can still access it directly via locators in the overflow spot, like `h[len]`, but if you sum over it, you should only get it if you ask for all bins, `h[::sum]`.

**Comment by henryiii** [comment]
Probably worth mentioning in the UHI spec, too.
