### ISSUE TITLE
Name of main import

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#60]
Currently, I have the name of the main folder as `boost.histogram`. Should we keep it that way, or change it? This is actually the main compiled library, so if we use `boost_histogram`, then we will need to call it `boost_histogram.core` or something like that, then import from it. Might need to look into keeping the `type` names reasonable in that case. @jpivarski expressed some concerns for boost.histogram, probably because we don't own boost on PyPI?

**Comment by jpivarski** [comment]
Owning `boost` would be a prerequisite for importing into `boost.histogram`, since changes to `boost/__init__.py` could lock you out of the use of that name. Even if you do own it, there's not a lot of value to using it as a namespace unless you expect there to be other, parallel `boost.XYZ` libraries.

Despite the ambiguity about `-` (sometimes used for package names) vs `_` (always used for import names), there's a precedent. Quite a few libraries use `-` for a package name and `_` for import. At worst, there's two things to try.

I don't think the `-` or `_` is ideal; somebody might have a better idea.

**Comment by HDembinski** [comment]
If there was no other package called boost, we could just grab the name and the package slot. Since there are issues using `boost` and we would like to avoid the `-` and `_` issue, how about using another name? I am thinking that maybe having `boost` in the name is not a good idea, since it this code is not officially reviewed by the Boost community and perhaps we should avoid any misunderstanding there.

What other names could we use? `bhistogram`?

**Comment by jpivarski** [comment]
`boosthistogram` would not be terrible. Long enough words are easier to visually separate, particularly if both are very familiar, like this.

But I think the "standard" thing to use for a PyPI package like this, for better or worse, is `boost-histogram` (`import boost_histogram`).

**Comment by henryiii** [comment]
There is a package called boost - It's tagline is "Boost automatically toots from users of the Mastodon social network" - and only has one 0.1 release a couple of years ago. It's unlikely to be a problem, but we can avoid it.

**Comment by HDembinski** [comment]
Just so that there is no misunderstanding, I am not fond of `bhistogram`, I am just brain-storming at this point. I think I can live with `boost-histogram` and `boost_histogram`. Users (except maybe me) will anyway not install `boost-histogram`, but `hist`, right? If `boost-histogram` is only used internally by `hist`, then we can live with this minor inconvenience.

**Comment by HDembinski** [comment]
Yes, that sounds good to me. I think the module should be called `boost_histogram` because that's the least surprising when you install a package called `boost-histogram`.

**Comment by henryiii** [comment]
This was done in #110. I'll leave this open for a few days for any discussions about the way it was done, names, etc.
