### ISSUE TITLE
[BUG] Sum of sliced histogram

### ISSUE THREAD

**Issue by Nollde** [scikit-hep/boost-histogram#621]
**Describe the bug**

When slicing a histogram, and summing over the sliced axis, the values which have been "sliced away" enter the sum.
I am not sure if this is a bug or an expected behaviour.
If the behaviour is expected, I would greatly appreciate if you could tell me how this operation should properly be done.

Issue may be linked to #281.

**Steps to reproduce**
```

In [1]: import boost_histogram as bh

In [2]: bh.__version__
Out[2]: '1.0.2'

In [3]: hist = bh.Histogram(
   ...:     bh.axis.StrCategory(["a", "b"]),
   ...:     bh.axis.Regular(1, 0, 2),
   ...:     storage=bh.storage.Int64(),
   ...: )

In [4]: hist.fill(["a", "a", "a", "b", "b"], [1, 1, 3, 1, 1])
Out[4]:
Histogram(
  StrCategory(['a', 'b']),
  Regular(1, 0, 2),
  storage=Int64()) # Sum: 4.0 (5.0 with flow)

In [5]: hist[:1, :]
Out[5]:
Histogram(
  StrCategory(['a']),
  Regular(1, 0, 2),
  storage=Int64()) # Sum: 2.0 (5.0 with flow)

In [6]: hist[:1, :][::sum,:]
Out[6]: Histogram(Regular(1, 0, 2), storage=Int64()) # Sum: 4.0 (5.0 with flow)  # sum includes values from bin "b"

In [7]: hist[:1, :].view()
Out[7]: array([[2]], dtype=uint64)

In [8]: hist[:1, :][::sum,:].view()
Out[8]: array([4], dtype=uint64)  # sum includes values from bin "b"
```

**Comment by henryiii** [comment]
This is the expected behavior. Leaving an endpoint off will include underflow or overflow; you should think of no endpoint as "infinite".  If you don't want this behavior, make the endpoints explicit (such as `[0:len:sum]`), or use an axis that does not have flow bins (`underflow=False`, `overflow=False` when you make the axis). For a category axis, there is only an overflow bin, and we don't have a no flow version (IIRC), so you should use the first suggestion.

**Comment by Nollde** [comment]
Hi @henryiii , thanks for your explanation.
As I can not easily change the code which does the sum, I circumenvented the problem by using two hsitograms.
Thank you for your help.
Closing the issue as this is the expected behavior.
