### ISSUE TITLE
`__copy__` and `__deepcopy__`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/boost-histogram#94]
Adding `__copy__` and `__deepcopy__` everywhere seems weird. Is pybind11 not calling the copy ctor of the C++ instance when a `__copy__` or `__deepcopy__` is requested?

I think a better solution that doing this in `register_histogram`
```
        .def("__deepcopy__",
             [](const histogram_t &self, py::object memo) {
                 histogram_t *a  = new histogram_t(self);
                 py::module copy = py::module::import("copy");
                 for(unsigned i = 0; i < a->rank(); i++) {
                     bh::unsafe_access::axis(*a, i).metadata() = copy.attr("deepcopy")(a->axis(i).metadata(), memo);
                 }
                 return a;
             })
```
is to add a copy ctor to `metadata_t` which does the deep copy. Then the deep copy is automatically done in the copy ctors of the axis types and by the copy ctor of histogram. Doing it in metadata_t is better encapsulation.

**Comment by HDembinski** [comment]
Everything besides metadata_t performs a deep copy already.

**Comment by HDembinski** [comment]
So what should we do, does this need more investigation?

**Comment by henryiii** [comment]
There was an investigation and lots of comments about it on the PyBind Gitter channel, so I *think* it is the best solution, but it is possible that there is a different or better way. Several versions of a copy ctor were tested. I think the most important thing is that you shouldn't inject a Python interaction into C++, as `h2 = h1` in C++ should not call a Python interaction due to the Python internal object; it should always be a shallow copy. Only an explicit request for a deep copy should copy the Python object, which is very expensive and cannot be done in threads. 

I need to check and see how PyBind handles `__copy__` and `__deepcopy__` if none are given, as I see it's in some places (storages, for example) that it seems like a default should be fine. Some of those might be removable.

**Comment by henryiii** [comment]
It looks like `__copy__` and `__deepcopy__` are needed for Python 2.7 to behave properly. Python 3 is quite happy if you remove them for accumulators and storages.

**Comment by HDembinski** [comment]
Do we have tests which fail if `__copy__` or `__deepcopy__` are removed?

**Comment by henryiii** [comment]
Yes, I tried removing them from accumulators and storages and the Python 2.7 tests bombed. That' how I know. :)

**Comment by henryiii** [comment]
These 10 tests failed: https://dev.azure.com/scikit-hep/boost-histogram/_build/results?buildId=1110

**Comment by HDembinski** [comment]
Ok, good, I just wanted to make sure that this is covered by unit tests. Then let's close this for now.
